version: '3'
services:
  # opq:
  #   image: opqofficial/opq:latest
  #   container_name: opq
  #   ports:
  #     - 8086:8086
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 100M
  #   environment:
  #     - token=*****
  #   restart: always
  redis-mahiro:
    image: redis:latest
    container_name: redis-mahiro
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always
  node-mahiro:
    image: yingci/mahiro:latest
    container_name: node-mahiro
    depends_on:
      - redis-mahiro
    ports:
      - 8086:8086
      - 8098:8098
      - 8099:8099
    links:
      - redis-mahiro
    volumes:
      - ../examples/simple/mahiro.db:/app/server/mahiro.db
      - ../examples/simple/test.ts:/app/server/index.ts
      